Alt-Text-Leslie-Chapter-7
thegetty/living-matter pull request #59
Opened 2022-06-24 00:02 UTC by leslie-martinez15

Added Alt-texts to the figures found in chapter 7

2022-06-24 00:29 UTC, Erin-Cecele requested changes
@leslie-martinez15 You did a great job drafting this alt-text! I've made some suggestions below, some are grammatical and others are more subjective. @geealbers will also be able to provide great advice. Default to anything he says over my suggestions ;-).

2022-06-24 00:29 UTC, Erin-Cecele commented on data/figures.yml
> +    alt: "Fingers holding up a measuring tape near the dried up brown skin with tweezers on the side"
In the alt text for Figure 7.8 you use a hyphen in "dried-up". Add the hyphen here to maintain consistency. 

Also, I think it should be "Fingers hold a ruler over the dried-up..." I know I said measuring tape when we spoke earlier, but I think ruler works better.

2022-06-24 00:29 UTC, Erin-Cecele commented on data/figures.yml
> +    alt: "A close-up view of the artist's back  after a portion of skin was removed "
There is an extra space between "back" and "after". Please delete.

2022-06-24 00:29 UTC, Erin-Cecele commented on data/figures.yml
> +    alt: "A close-up view of skin inside a container submerged in a liquid being measured"
The way it's written now makes it sound like the container is submerged in liquid. What do you think of this option: "A container that holds the removed skin floating in liquid is measured with a ruler." Or something to that effect.

2022-06-24 00:29 UTC, Erin-Cecele commented on data/figures.yml
> +    alt: "Soaked up yellow skin that is placed in a blue biological mat pinned by entomology steel pins"
I think "soaked up" is confusing. Maybe "saturated"? What do you think of this edit: "Saturated yellow skin is held in place on a blue biological mat by entomology steel pins."

2022-06-24 00:29 UTC, Erin-Cecele commented on data/figures.yml
> +    alt: "The blacken dried-up skin placed in a golden medal with the artist's name inscribed in it"
This should be "blackened" and "with the artist's name inscribed on it".

2022-06-24 00:29 UTC, Erin-Cecele commented on data/figures.yml
> +    alt: "A hand holds a measuring tape near the dried brown skin with tweezer"
This is the wrong caption for this image.

2022-06-24 00:29 UTC, Erin-Cecele commented on data/figures.yml
> +    alt: "Back tattoo that says award in spanish with scar on the side from the operation"
I'm not sure how best to handle this one. I would love to hear @geealbers's advice.

2022-06-27 15:33 UTC, geealbers reviewed
Leslie, I think you've done really well on these first alt texts, thank you!

Please go back and address Erin's comments by making any necessary changes in the figures.yml file in this same branch, and then committing and pushing them to GitHub. Those changes will then automatically be added to this Pull Request for us to review one last time before merging.

Let me know if you have any questions.

2022-06-27 15:33 UTC, geealbers commented on data/figures.yml
> +    alt: "Back tattoo that says award in spanish with scar on the side from the operation"
@leslie-martinez15, because the caption already says "scar and tattoo on the artist’s body" I'd focus the alt text on the tattoo itself, including its full text and perhaps a description of the lettering.

2022-06-27 16:39 UTC, merged