Fixed Alt-Texts
thegetty/living-matter pull request #60
Opened 2022-06-27 17:40 UTC by leslie-martinez15

Alt-texts that still needed some more tweaking have been fixed

2022-07-01 23:30 UTC, geealbers requested changes
@leslie-martinez15 these are looking really good! Your word choices are so descriptive and lovely to read. I'm so glad you were able to get to so many essays this week.

I've made some specific notes for you to address when you can. There were also some scattered spelling/typo errors throughout that I didn't always mark. I'd recommend going back and running them through a spellcheck to see what you can find. Atom should be highlighting misspellings, but if not, you could copy and past the whole file into a Word doc if that helps you find them. You might also find them just by going back and re-reading carefully once you have a little distance from them.

Once you've corrected these, we'll merge these into the final publication! Thanks so much for doing this work. It's such a benefit to us and our readers!

2022-07-01 23:30 UTC, geealbers commented on data/figures.yml
> +    alt: "A closer view to the hanging mushroom production polyethylene bags"     # caption and credit info in shortcode
The way you've written this description, it feels like it assumes the reader has read/heard the alt text for the previous figure (8.3a). I think we'd rather avoid this, and should instead write it as if the other figure wasn't there. Could you do that?

And I'm going to make a note for @dimrkh because I think this is something worth addressing in our guidelines. Thanks!

2022-07-01 23:30 UTC, geealbers commented on data/figures.yml
> +    alt: "A wooden figure resembling the crucifixion ontop of circular blood stain pages"
"blood stained"

2022-07-01 23:30 UTC, geealbers commented on data/figures.yml
> +    alt: "Two women holding a converstion in front of a orange 3-D media art piece"
"an orange"

2022-07-01 23:30 UTC, geealbers commented on data/figures.yml
> +    alt: "Gray pumice stone with white cracks running towards the right side to the black mortar and bird seeds in the corner"
Nice!

2022-07-01 23:30 UTC, geealbers commented on data/figures.yml
> +    alt: "A black box with bright magenta sticker on the left and white bold lettering that writes Mexico in the right corner and Semefo, Lavatio Corporis in the middle"
Perhaps "bold lettering that says" instead of "bold lettering that writes"?

2022-07-01 23:30 UTC, geealbers commented on data/figures.yml
> +    alt: "A book with thick blue edges with a spine of an antique book, displaying a 3-D seahore and 4 insects ontop of a cover with drawings"
"on top" should be two words. I think there was maybe another instance of this above if you can search for it

2022-07-01 23:30 UTC, geealbers commented on data/figures.yml
> +    alt: "A glass case showcasing serval medium-size and large size book sculptures"
there's a typo in "several"

2022-07-01 23:30 UTC, geealbers commented on data/figures.yml
> +    alt: "An orange, three-layer tackle box with trinkets and objects taking up every space"
Another really good one

2022-07-01 23:30 UTC, geealbers commented on data/figures.yml
> +    alt: "A yellow sardine can, with soggy deteriorating mold coming from it's right side"
"its" instead of "it's"

2022-07-01 23:30 UTC, geealbers commented on data/figures.yml
> +    alt: "Two gigantic black and white photo of hands pasted on the wall, with food on top of tapestry and newspapers scattered in front of the photograph. "
"photo" should be plural

2022-07-01 23:30 UTC, geealbers commented on data/figures.yml
> +    alt: "A concept map demostrating the different ways people can take on conserving art pieces that have living oraganisms"
missing "n" in "demonstrating"

2022-07-01 23:30 UTC, geealbers commented on data/figures.yml
> +    alt: A close-up view of a blown glass bulb with a blue butter butterfly on top with other bulbs surrounding it"
Just missing the first " (quote) to start the sentence

2022-07-05 20:48 UTC, leslie-martinez15 commented on data/figures.yml
>    - id: "fig-8-4c"
Figure 8.4-C does not appear on the Quire site, can I remove this?

2022-07-11 20:12 UTC, geealbers approved these changes

2022-07-11 20:18 UTC, merged