Add Ch15 Alt Text
thegetty/living-matter pull request #61
Opened 2022-07-12 21:28 UTC by skolacha

I added alt text for all figures in Chapter 15!

2022-07-12 21:42 UTC, geealbers requested changes
Looks great. And so quickly done! I've just note one small formatting change that needs to be made. Thanks!

2022-07-12 21:46 UTC, skolacha commented on data/figures.yml
> +    alt:"Three-quarter view of row of patterned red, blue, and plaid blankets standing upright in rectangular formations "
Great, thanks for letting me know!

2022-08-29 18:43 UTC, geealbers approved these changes

2022-08-29 18:44 UTC, geealbers commented
@skolacha I forgot to review and merge these alt texts in before you left, but they look great and I'm merging them in now. thanks so much for doing them!

2022-08-29 18:44 UTC, merged